"""
AutoSRE Deployment Safety Module

Enterprise-grade deployment safety capabilities providing:
- Canary analysis for safe progressive rollouts
- Automated rollback based on metrics and health checks
- Pre/post deployment verification
- Deployment gates with policy enforcement

Enables safe deployments with automatic canary analysis, health verification,
and intelligent rollback decisions based on SLOs and metrics.

Usage:
    from autosre.deploy import (
        # Canary Analysis
        CanaryAnalyzer, CanaryConfig, CanaryResult, CanaryVerdict,
        MetricComparison, StatisticalTest, CanaryMetric,
        # Rollback
        RollbackManager, RollbackConfig, RollbackResult, RollbackReason,
        RollbackStrategy, RollbackTrigger, AutoRollbackPolicy,
        # Verification
        DeploymentVerifier, VerificationConfig, VerificationResult,
        HealthCheck, ReadinessCheck, SmokeTest, VerificationStage,
        # Gates
        DeploymentGate, GateConfig, GateResult, GatePolicy,
        ApprovalGate, MetricGate, TimeGate, ManualGate,
    )
"""

from autosre.deploy.canary import (
    CanaryAnalyzer,
    CanaryConfig,
    CanaryResult,
    CanaryVerdict,
    CanaryPhase,
    CanaryMetric,
    MetricComparison,
    ComparisonResult,
    StatisticalTest,
    TestType,
    CanaryWeight,
    TrafficSplit,
    CanaryPromotion,
    PromotionCriteria,
    CanaryReport,
    CanaryTimeline,
    CanaryEvent,
)
from autosre.deploy.rollback import (
    RollbackManager,
    RollbackConfig,
    RollbackResult,
    RollbackStatus,
    RollbackReason,
    RollbackStrategy,
    RollbackTrigger,
    TriggerCondition,
    AutoRollbackPolicy,
    RollbackExecution,
    RollbackAction,
    RollbackSnapshot,
    RollbackHistory,
    RollbackNotifier,
)
from autosre.deploy.verification import (
    DeploymentVerifier,
    VerificationConfig,
    VerificationResult,
    VerificationStatus,
    VerificationStage,
    HealthCheck,
    HealthCheckResult,
    HealthCheckType,
    ReadinessCheck,
    ReadinessResult,
    SmokeTest,
    SmokeTestResult,
    SmokeTestSuite,
    PreDeploymentCheck,
    PostDeploymentCheck,
    VerificationReport,
    VerificationTimeline,
)
from autosre.deploy.gates import (
    DeploymentGate,
    GateConfig,
    GateResult,
    GateStatus,
    GatePolicy,
    GateType,
    GateEvaluator,
    ApprovalGate,
    ApprovalConfig,
    ApprovalRequest,
    ApprovalDecision,
    MetricGate,
    MetricGateConfig,
    MetricCondition,
    TimeGate,
    TimeGateConfig,
    TimeWindow,
    ManualGate,
    ManualGateConfig,
    GatePipeline,
    PipelineStage,
    PipelineResult,
)

__all__ = [
    # Canary Analysis
    "CanaryAnalyzer",
    "CanaryConfig",
    "CanaryResult",
    "CanaryVerdict",
    "CanaryPhase",
    "CanaryMetric",
    "MetricComparison",
    "ComparisonResult",
    "StatisticalTest",
    "TestType",
    "CanaryWeight",
    "TrafficSplit",
    "CanaryPromotion",
    "PromotionCriteria",
    "CanaryReport",
    "CanaryTimeline",
    "CanaryEvent",
    # Rollback
    "RollbackManager",
    "RollbackConfig",
    "RollbackResult",
    "RollbackStatus",
    "RollbackReason",
    "RollbackStrategy",
    "RollbackTrigger",
    "TriggerCondition",
    "AutoRollbackPolicy",
    "RollbackExecution",
    "RollbackAction",
    "RollbackSnapshot",
    "RollbackHistory",
    "RollbackNotifier",
    # Verification
    "DeploymentVerifier",
    "VerificationConfig",
    "VerificationResult",
    "VerificationStatus",
    "VerificationStage",
    "HealthCheck",
    "HealthCheckResult",
    "HealthCheckType",
    "ReadinessCheck",
    "ReadinessResult",
    "SmokeTest",
    "SmokeTestResult",
    "SmokeTestSuite",
    "PreDeploymentCheck",
    "PostDeploymentCheck",
    "VerificationReport",
    "VerificationTimeline",
    # Gates
    "DeploymentGate",
    "GateConfig",
    "GateResult",
    "GateStatus",
    "GatePolicy",
    "GateType",
    "GateEvaluator",
    "ApprovalGate",
    "ApprovalConfig",
    "ApprovalRequest",
    "ApprovalDecision",
    "MetricGate",
    "MetricGateConfig",
    "MetricCondition",
    "TimeGate",
    "TimeGateConfig",
    "TimeWindow",
    "ManualGate",
    "ManualGateConfig",
    "GatePipeline",
    "PipelineStage",
    "PipelineResult",
]
