"""
AutoSRE Service Mesh Integration Module

Enterprise-grade service mesh integration providing:
- Istio service mesh management and observability
- Linkerd lightweight mesh integration
- Traffic management (canary, A/B testing, blue-green)
- Mesh observability and telemetry
- mTLS certificate management
- Circuit breaker and retry policies

Enables deep service mesh integration for incident response,
traffic control, and service-level observability.

Usage:
    from autosre.mesh import (
        # Istio
        IstioClient, VirtualService, DestinationRule, Gateway,
        AuthorizationPolicy, PeerAuthentication, RequestAuthentication,
        # Linkerd
        LinkerdClient, ServiceProfile, TrafficSplit, Server,
        ServerAuthorization, LinkerdPolicy,
        # Traffic Management
        TrafficManager, CanaryDeployment, BlueGreenDeployment,
        ABTest, TrafficShift, WeightedRoute, HeaderMatch,
        # Observability
        MeshObserver, ServiceMetrics, RequestTrace, ServiceTopology,
        HealthCheck, LatencyHistogram, ErrorRateMetric,
    )
"""

from autosre.mesh.istio import (
    IstioClient,
    IstioConfig,
    VirtualService,
    VirtualServiceSpec,
    DestinationRule,
    DestinationRuleSpec,
    Gateway,
    GatewaySpec,
    ServiceEntry,
    ServiceEntrySpec,
    Sidecar,
    SidecarSpec,
    AuthorizationPolicy,
    AuthorizationPolicySpec,
    PeerAuthentication,
    PeerAuthenticationSpec,
    RequestAuthentication,
    RequestAuthenticationSpec,
    EnvoyFilter,
    EnvoyFilterSpec,
    WorkloadEntry,
    WorkloadGroup,
    IstioOperator,
    HTTPRoute,
    HTTPMatchRequest,
    HTTPRouteDestination,
    StringMatch,
    HTTPRetry,
    HTTPFaultInjection,
    HTTPRedirect,
    HTTPRewrite,
    TrafficPolicy,
    ConnectionPoolSettings,
    OutlierDetection,
    LoadBalancerSettings,
    TLSSettings,
    PortSelector,
    WorkloadSelector,
    IstioMeshStatus,
    IstiodStatus,
)
from autosre.mesh.linkerd import (
    LinkerdClient,
    LinkerdConfig,
    ServiceProfile,
    ServiceProfileSpec,
    TrafficSplit,
    TrafficSplitSpec,
    Server,
    ServerSpec,
    ServerAuthorization,
    ServerAuthorizationSpec,
    HTTPRoute as LinkerdHTTPRoute,
    LinkerdPolicy,
    LinkerdPolicySpec,
    RetryBudget,
    RouteSpec,
    ResponseClass,
    LinkerdMeshStatus,
    LinkerdProxyStatus,
    MeshTLSStatus,
    LinkerdIdentity,
)
from autosre.mesh.traffic import (
    TrafficManager,
    TrafficManagerConfig,
    CanaryDeployment,
    CanaryConfig,
    CanaryStatus,
    CanaryMetrics,
    BlueGreenDeployment,
    BlueGreenConfig,
    BlueGreenStatus,
    ABTest,
    ABTestConfig,
    ABTestResult,
    TrafficShift,
    TrafficShiftStrategy,
    WeightedRoute,
    HeaderMatch,
    HeaderMatchType,
    MirrorConfig,
    FaultConfig,
    RetryConfig,
    TimeoutConfig,
    CircuitBreakerConfig,
    RateLimitConfig,
    TrafficSnapshot,
    RollbackConfig,
)
from autosre.mesh.observability import (
    MeshObserver,
    MeshObserverConfig,
    ServiceMetrics,
    RequestMetrics,
    LatencyMetrics,
    ErrorMetrics,
    ThroughputMetrics,
    RequestTrace,
    TraceSpan,
    TraceContext,
    ServiceTopology,
    ServiceNode,
    ServiceEdge,
    TopologySnapshot,
    HealthCheck,
    HealthCheckResult,
    HealthCheckType,
    LatencyHistogram,
    LatencyPercentile,
    ErrorRateMetric,
    ErrorCategory,
    GoldenSignals,
    SLOCompliance,
    MeshAlert,
    AlertSeverity,
    AlertCondition,
)

__all__ = [
    # Istio
    "IstioClient",
    "IstioConfig",
    "VirtualService",
    "VirtualServiceSpec",
    "DestinationRule",
    "DestinationRuleSpec",
    "Gateway",
    "GatewaySpec",
    "ServiceEntry",
    "ServiceEntrySpec",
    "Sidecar",
    "SidecarSpec",
    "AuthorizationPolicy",
    "AuthorizationPolicySpec",
    "PeerAuthentication",
    "PeerAuthenticationSpec",
    "RequestAuthentication",
    "RequestAuthenticationSpec",
    "EnvoyFilter",
    "EnvoyFilterSpec",
    "WorkloadEntry",
    "WorkloadGroup",
    "IstioOperator",
    "HTTPRoute",
    "HTTPMatchRequest",
    "HTTPRouteDestination",
    "StringMatch",
    "HTTPRetry",
    "HTTPFaultInjection",
    "HTTPRedirect",
    "HTTPRewrite",
    "TrafficPolicy",
    "ConnectionPoolSettings",
    "OutlierDetection",
    "LoadBalancerSettings",
    "TLSSettings",
    "PortSelector",
    "WorkloadSelector",
    "IstioMeshStatus",
    "IstiodStatus",
    # Linkerd
    "LinkerdClient",
    "LinkerdConfig",
    "ServiceProfile",
    "ServiceProfileSpec",
    "TrafficSplit",
    "TrafficSplitSpec",
    "Server",
    "ServerSpec",
    "ServerAuthorization",
    "ServerAuthorizationSpec",
    "LinkerdHTTPRoute",
    "LinkerdPolicy",
    "LinkerdPolicySpec",
    "RetryBudget",
    "RouteSpec",
    "ResponseClass",
    "LinkerdMeshStatus",
    "LinkerdProxyStatus",
    "MeshTLSStatus",
    "LinkerdIdentity",
    # Traffic Management
    "TrafficManager",
    "TrafficManagerConfig",
    "CanaryDeployment",
    "CanaryConfig",
    "CanaryStatus",
    "CanaryMetrics",
    "BlueGreenDeployment",
    "BlueGreenConfig",
    "BlueGreenStatus",
    "ABTest",
    "ABTestConfig",
    "ABTestResult",
    "TrafficShift",
    "TrafficShiftStrategy",
    "WeightedRoute",
    "HeaderMatch",
    "HeaderMatchType",
    "MirrorConfig",
    "FaultConfig",
    "RetryConfig",
    "TimeoutConfig",
    "CircuitBreakerConfig",
    "RateLimitConfig",
    "TrafficSnapshot",
    "RollbackConfig",
    # Observability
    "MeshObserver",
    "MeshObserverConfig",
    "ServiceMetrics",
    "RequestMetrics",
    "LatencyMetrics",
    "ErrorMetrics",
    "ThroughputMetrics",
    "RequestTrace",
    "TraceSpan",
    "TraceContext",
    "ServiceTopology",
    "ServiceNode",
    "ServiceEdge",
    "TopologySnapshot",
    "HealthCheck",
    "HealthCheckResult",
    "HealthCheckType",
    "LatencyHistogram",
    "LatencyPercentile",
    "ErrorRateMetric",
    "ErrorCategory",
    "GoldenSignals",
    "SLOCompliance",
    "MeshAlert",
    "AlertSeverity",
    "AlertCondition",
]
