"""
AutoSRE - Open-source AI SRE Agent

Built foundation-first: context store, evals, sandbox, then agent logic.

v2 Architecture:
- Orchestrator: Investigation flow coordination
- Memory: Episodic memory for past incidents
- Topology: Service graph and dependencies
- Agents: Planner, Synthesizer, Writeup
- LLM: Multi-provider routing
- Skills: Kubernetes, Metrics, Logs
"""

__version__ = "0.2.0"
__author__ = "OpenSRE Community"

# Core v2 exports
from autosre.orchestrator import Orchestrator, Investigation
from autosre.memory import EpisodicMemory, Episode, MemoryQuery
from autosre.topology import ServiceGraph, ServiceNode
from autosre.agents import (
    Alert,
    Hypothesis,
    Evidence,
    AgentResult,
    InvestigationState,
    InvestigationPlan,
    Planner,
    AVAILABLE_AGENTS,
    Synthesizer,
    Synthesis,
    WriteupGenerator,
    IncidentReport,
)
from autosre.llm import LLMRouter
from autosre.reporters import TerminalReporter

# On-call and Postmortem (v2.1)
from autosre.alerts.quality import (
    AlertQualityValidator,
    AlertQualityResult,
    REQUIRED_ALERT_FIELDS,
)
from autosre.oncall.load import (
    OnCallLoadTracker,
    ShiftStatus,
    LoadStatus,
    MAX_INCIDENTS_PER_SHIFT,
    SHIFT_HOURS,
)
from autosre.postmortem.generator import (
    PostmortemGenerator,
    PostmortemDraft,
    ActionItem,
    ActionPriority,
    AIPerformanceReview,
)
from autosre.postmortem.policy import (
    PostmortemPolicy,
    PostmortemTrigger,
    TriggerType,
    PolicyConfig,
    load_policy_from_yaml,
)
from autosre.utils.deliberate import (
    DeliberateReasoner,
    DeliberationRecord,
    PAUSE_CHECKLIST_PROMPT,
)

# Multi-Tenancy (v2.2) - Enterprise SaaS support
from autosre.tenancy import (
    Tenant,
    TenantTier,
    TenantStatus,
    Workspace,
    WorkspaceType,
    Team,
    TeamRole,
    TenantContext,
    TenantIsolation,
    get_current_tenant,
    tenant_context,
    QuotaManager,
    QuotaType,
    QuotaExceededError,
    UsageTracker,
    BillingService,
    TenantMiddleware,
)

# Incident Communications (v2.4) - Automated incident communications
from autosre.comms import (
    StatusPageClient,
    StatusPageIncident,
    StatusPageUpdate,
    ComponentStatus,
    IncidentStatus,
    IncidentImpact,
    Component,
    StatusPageConfig,
    WarRoom,
    WarRoomState,
    WarRoomRole,
    WarRoomParticipant,
    WarRoomEvent,
    WarRoomEventType,
    WarRoomCoordinator,
    WarRoomConfig,
    WarRoomTimeline,
    Stakeholder,
    StakeholderGroup,
    StakeholderPriority,
    NotificationChannel,
    NotificationStatus,
    StakeholderNotifier,
    EscalationPolicy,
    EscalationLevel,
    MessageTemplate,
    TemplateContext,
    TemplateEngine,
    TemplateRegistry,
    get_builtin_templates,
)

# Chaos Engineering (v2.3) - Resilience testing
from autosre.chaos import (
    ChaosExperiment,
    ExperimentState,
    ExperimentResult,
    ExperimentConfig,
    ExperimentType,
    TargetSelector,
    ExperimentSchedule,
    ExperimentRunner,
    Fault,
    FaultType,
    FaultInjector,
    PodKillFault,
    NetworkDelayFault,
    CPUStressFault,
    MemoryStressFault,
    GameDay,
    GameDayState,
    GameDayResult,
    GameDayScenario,
    GameDayScheduler,
    GameDayRunner,
    SafetyChecker,
    SafetyRule,
    SafetyViolation,
    BlastRadius,
    BlastRadiusConfig,
    SafetyPolicy,
    SafetyLevel,
    CircuitBreaker,
    ChaosReport,
    ExperimentMetrics,
    ReportGenerator,
    ResilienceScore,
)

# Plugin System (v2.6) - Extensibility and custom integrations
from autosre.plugins import (
    # Base classes
    Plugin,
    SkillPlugin,
    IntegrationPlugin,
    HookPlugin,
    MiddlewarePlugin,
    # Configuration
    PluginConfig,
    PluginContext,
    PluginResult,
    # Metadata
    PluginMetadata,
    PluginState,
    PluginType,
    PluginPriority,
    PluginCapability,
    # Registry
    PluginRegistry,
    RegistryConfig,
    RegistryEvent,
    get_registry as get_plugin_registry,
    register_plugin,
    unregister_plugin,
    # Loader
    PluginLoader,
    LoaderConfig,
    discover_plugins,
    load_plugin,
    load_plugins_from_directory,
)

# AI Guardrails (v2.5) - Enterprise AI safety
from autosre.guardrails import (
    # Validators
    Validator as GuardrailValidator,
    ValidationResult,
    ValidationSeverity,
    InputValidator,
    InputValidationConfig,
    ContentCategory,
    InputSanitizer,
    SanitizationRule,
    SanitizationType,
    OutputValidator,
    OutputValidationConfig,
    OutputClassification,
    ContentFilter,
    FilterAction,
    PromptValidator,
    PromptInjectionDetector,
    InjectionType,
    SchemaValidator,
    ResponseSchemaConfig,
    # Policies
    SafetyPolicy as GuardrailSafetyPolicy,
    PolicyEngine,
    PolicyResult,
    PolicyAction,
    PolicyScope,
    RiskLevel,
    RiskAssessment,
    RiskFactor,
    RiskThreshold,
    ActionPolicy,
    ActionRestriction,
    ActionCategory,
    AllowedAction,
    RateLimiter,
    RateLimitConfig,
    RateLimitScope,
    ContextPolicy,
    SensitiveDataPolicy,
    DataClassification,
    # Approval
    ApprovalWorkflow,
    ApprovalRequest,
    ApprovalDecision,
    ApprovalStatus,
    ApprovalLevel,
    Approver,
    ApproverGroup,
    ApprovalPolicy,
    ApprovalStrategy,
    EscalationConfig,
    EscalationRule,
    ApprovalNotifier,
    NotificationConfig as ApprovalNotificationConfig,
    # Audit
    AuditTrail,
    AuditEntry,
    AuditCategory,
    AuditSeverity,
    AuditVerifier,
    IntegrityCheck,
    HashChain,
    AuditStorage,
    AuditQuery,
    AuditReport,
    ComplianceChecker,
    ComplianceFramework,
    ComplianceReport,
)

# Cost Optimization (v2.4) - FinOps for SRE
from autosre.cost import (
    CostAnalyzer,
    CostBreakdown,
    CostTrend,
    CostAllocation,
    CostMetric,
    CloudProvider,
    ResourceType,
    CostRecommendation,
    RecommendationType,
    RecommendationPriority,
    RecommendationEngine,
    SavingsEstimate,
    RecommendationStatus,
    RightsizingAnalyzer,
    RightsizingRecommendation,
    ResourceUtilization,
    InstanceSpec,
    RightsizingAction,
    UtilizationThreshold,
    CostForecaster,
    CostForecast,
    BudgetAlert,
    BudgetStatus,
    ForecastModel,
    SpendingTrend,
    AnomalyDetector,
    CostAnomaly,
)

# Workflow Automation (v2.3) - Temporal/Argo-inspired workflow engine
from autosre.workflows import (
    # Engine
    WorkflowEngine,
    WorkflowExecution,
    ExecutionStatus,
    StepExecution,
    WorkflowContext,
    # DSL
    WorkflowDefinition,
    WorkflowParser,
    WorkflowValidator,
    parse_workflow,
    parse_workflow_file,
    # Steps
    Step,
    ActionStep,
    ConditionStep,
    LoopStep,
    ParallelStep,
    SubWorkflowStep,
    StepResult,
    StepStatus,
    # Triggers
    Trigger,
    AlertTrigger,
    ScheduleTrigger,
    WebhookTrigger,
    ManualTrigger,
    TriggerEvent,
    TriggerManager,
    # Templates
    WorkflowTemplate,
    TemplateRegistry,
    get_builtin_templates,
)

# Foundation (v1) exports - maintained for compatibility
from autosre.foundation.context_store import ContextStore
from autosre.foundation.models import Service, Ownership, ChangeEvent
from autosre.logging import get_logger, configure_logging
from autosre.exceptions import (
    AutoSREError,
    ConfigurationError,
    ConnectionError,
    ContextError,
    AgentError,
    SandboxError,
    EvalError,
)

__all__ = [
    # Version
    "__version__",
    # Core v2
    "Orchestrator",
    "Investigation",
    "EpisodicMemory",
    "Episode",
    "MemoryQuery",
    "ServiceGraph",
    "ServiceNode",
    "Alert",
    "Hypothesis",
    "Evidence",
    "AgentResult",
    "InvestigationState",
    "InvestigationPlan",
    "Planner",
    "AVAILABLE_AGENTS",
    "Synthesizer",
    "Synthesis",
    "WriteupGenerator",
    "IncidentReport",
    "LLMRouter",
    "TerminalReporter",
    # On-call & Postmortem (v2.1)
    "AlertQualityValidator",
    "AlertQualityResult",
    "REQUIRED_ALERT_FIELDS",
    "OnCallLoadTracker",
    "ShiftStatus",
    "LoadStatus",
    "MAX_INCIDENTS_PER_SHIFT",
    "SHIFT_HOURS",
    "PostmortemGenerator",
    "PostmortemDraft",
    "ActionItem",
    "ActionPriority",
    "AIPerformanceReview",
    "PostmortemPolicy",
    "PostmortemTrigger",
    "TriggerType",
    "PolicyConfig",
    "load_policy_from_yaml",
    "DeliberateReasoner",
    "DeliberationRecord",
    "PAUSE_CHECKLIST_PROMPT",
    # Multi-Tenancy (v2.2)
    "Tenant",
    "TenantTier",
    "TenantStatus",
    "Workspace",
    "WorkspaceType",
    "Team",
    "TeamRole",
    "TenantContext",
    "TenantIsolation",
    "get_current_tenant",
    "tenant_context",
    "QuotaManager",
    "QuotaType",
    "QuotaExceededError",
    "UsageTracker",
    "BillingService",
    "TenantMiddleware",
    # Incident Communications (v2.4)
    "StatusPageClient",
    "StatusPageIncident",
    "StatusPageUpdate",
    "ComponentStatus",
    "IncidentStatus",
    "IncidentImpact",
    "Component",
    "StatusPageConfig",
    "WarRoom",
    "WarRoomState",
    "WarRoomRole",
    "WarRoomParticipant",
    "WarRoomEvent",
    "WarRoomEventType",
    "WarRoomCoordinator",
    "WarRoomConfig",
    "WarRoomTimeline",
    "Stakeholder",
    "StakeholderGroup",
    "StakeholderPriority",
    "NotificationChannel",
    "NotificationStatus",
    "StakeholderNotifier",
    "EscalationPolicy",
    "EscalationLevel",
    "MessageTemplate",
    "TemplateContext",
    "TemplateEngine",
    # Workflow Automation (v2.3)
    "WorkflowEngine",
    "WorkflowExecution",
    "ExecutionStatus",
    "StepExecution",
    "WorkflowContext",
    "WorkflowDefinition",
    "WorkflowParser",
    "WorkflowValidator",
    "parse_workflow",
    "parse_workflow_file",
    "Step",
    "ActionStep",
    "ConditionStep",
    "LoopStep",
    "ParallelStep",
    "SubWorkflowStep",
    "StepResult",
    "StepStatus",
    "Trigger",
    "AlertTrigger",
    "ScheduleTrigger",
    "WebhookTrigger",
    "ManualTrigger",
    "TriggerEvent",
    "TriggerManager",
    "WorkflowTemplate",
    "TemplateRegistry",
    "get_builtin_templates",
    # Cost Optimization (v2.4)
    "CostAnalyzer",
    "CostBreakdown",
    "CostTrend",
    "CostAllocation",
    "CostMetric",
    "CloudProvider",
    "ResourceType",
    "CostRecommendation",
    "RecommendationType",
    "RecommendationPriority",
    "RecommendationEngine",
    "SavingsEstimate",
    "RecommendationStatus",
    "RightsizingAnalyzer",
    "RightsizingRecommendation",
    "ResourceUtilization",
    "InstanceSpec",
    "RightsizingAction",
    "UtilizationThreshold",
    "CostForecaster",
    "CostForecast",
    "BudgetAlert",
    "BudgetStatus",
    "ForecastModel",
    "SpendingTrend",
    "AnomalyDetector",
    "CostAnomaly",
    # AI Guardrails (v2.5)
    "GuardrailValidator",
    "ValidationResult",
    "ValidationSeverity",
    "InputValidator",
    "InputValidationConfig",
    "ContentCategory",
    "InputSanitizer",
    "SanitizationRule",
    "SanitizationType",
    "OutputValidator",
    "OutputValidationConfig",
    "OutputClassification",
    "ContentFilter",
    "FilterAction",
    "PromptValidator",
    "PromptInjectionDetector",
    "InjectionType",
    "SchemaValidator",
    "ResponseSchemaConfig",
    "GuardrailSafetyPolicy",
    "PolicyEngine",
    "PolicyResult",
    "PolicyAction",
    "PolicyScope",
    "RiskLevel",
    "RiskAssessment",
    "RiskFactor",
    "RiskThreshold",
    "ActionPolicy",
    "ActionRestriction",
    "ActionCategory",
    "AllowedAction",
    "RateLimiter",
    "RateLimitConfig",
    "RateLimitScope",
    "ContextPolicy",
    "SensitiveDataPolicy",
    "DataClassification",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "ApprovalDecision",
    "ApprovalStatus",
    "ApprovalLevel",
    "Approver",
    "ApproverGroup",
    "ApprovalPolicy",
    "ApprovalStrategy",
    "EscalationConfig",
    "EscalationRule",
    "ApprovalNotifier",
    "ApprovalNotificationConfig",
    "AuditTrail",
    "AuditEntry",
    "AuditCategory",
    "AuditSeverity",
    "AuditVerifier",
    "IntegrityCheck",
    "HashChain",
    "AuditStorage",
    "AuditQuery",
    "AuditReport",
    "ComplianceChecker",
    "ComplianceFramework",
    "ComplianceReport",
    # Plugin System (v2.6)
    "Plugin",
    "SkillPlugin",
    "IntegrationPlugin",
    "HookPlugin",
    "MiddlewarePlugin",
    "PluginConfig",
    "PluginContext",
    "PluginResult",
    "PluginMetadata",
    "PluginState",
    "PluginType",
    "PluginPriority",
    "PluginCapability",
    "PluginRegistry",
    "RegistryConfig",
    "RegistryEvent",
    "get_plugin_registry",
    "register_plugin",
    "unregister_plugin",
    "PluginLoader",
    "LoaderConfig",
    "discover_plugins",
    "load_plugin",
    "load_plugins_from_directory",
    # Foundation (v1)
    "ContextStore",
    "Service",
    "Ownership",
    "ChangeEvent",
    # Logging
    "get_logger",
    "configure_logging",
    # Exceptions
    "AutoSREError",
    "ConfigurationError",
    "ConnectionError",
    "ContextError",
    "AgentError",
    "SandboxError",
    "EvalError",
]
