"""
AutoSRE - Open-source AI SRE Agent

Built foundation-first: context store, evals, sandbox, then agent logic.

v2 Architecture:
- Orchestrator: Investigation flow coordination
- Memory: Episodic memory for past incidents
- Topology: Service graph and dependencies
- Agents: Planner, Synthesizer, Writeup
- LLM: Multi-provider routing
- Skills: Kubernetes, Metrics, Logs
"""

__version__ = "0.2.0"
__author__ = "OpenSRE Community"

# Core v2 exports
from autosre.orchestrator import Orchestrator, Investigation
from autosre.memory import EpisodicMemory, Episode, MemoryQuery
from autosre.topology import ServiceGraph, ServiceNode
from autosre.agents import (
    Alert,
    Hypothesis,
    Evidence,
    AgentResult,
    InvestigationState,
    InvestigationPlan,
    Planner,
    AVAILABLE_AGENTS,
    Synthesizer,
    Synthesis,
    WriteupGenerator,
    IncidentReport,
)
from autosre.llm import LLMRouter
from autosre.reporters import TerminalReporter

# On-call and Postmortem (v2.1)
from autosre.alerts.quality import (
    AlertQualityValidator,
    AlertQualityResult,
    REQUIRED_ALERT_FIELDS,
)
from autosre.oncall.load import (
    OnCallLoadTracker,
    ShiftStatus,
    LoadStatus,
    MAX_INCIDENTS_PER_SHIFT,
    SHIFT_HOURS,
)

# On-Call Management v2.1+ (Extended)
from autosre.oncall.schedule import (
    ScheduleType,
    DayOfWeek,
    ScheduleRestrictionType,
    OverrideReason,
    TimeRange,
    ScheduleRestriction,
    ScheduleLayer,
    ScheduleOverride,
    OnCallSchedule,
    ScheduleManager,
    create_weekly_schedule,
    create_follow_the_sun_schedule,
)
from autosre.oncall.rotation import (
    RotationType,
    RotationFrequency,
    UserAvailability,
    RotationRole,
    UserStats,
    UserAvailabilityWindow,
    RotationConstraint,
    RotationMember,
    Rotation,
    RotationManager,
    create_simple_rotation,
    create_tiered_rotation,
)
from autosre.oncall.escalation import (
    EscalationTrigger,
    NotificationMethod,
    EscalationStatus as OnCallEscalationStatus,
    TargetType,
    NotificationTarget,
    EscalationLevel as OnCallEscalationLevel,
    EscalationPolicy as OnCallEscalationPolicy,
    EscalationEvent,
    ActiveEscalation,
    EscalationEngine,
    create_simple_policy as create_simple_escalation_policy,
    create_tiered_policy as create_tiered_escalation_policy,
)
from autosre.oncall.handoff import (
    HandoffStatus,
    HandoffItemType,
    HandoffItemPriority,
    HandoffItemStatus,
    HandoffItem,
    IncidentSummary,
    ShiftSummary,
    Handoff,
    HandoffTemplate,
    HandoffManager,
    create_quick_handoff,
    generate_handoff_checklist,
)
from autosre.postmortem.generator import (
    PostmortemGenerator,
    PostmortemDraft,
    ActionItem,
    ActionPriority,
    AIPerformanceReview,
)
from autosre.postmortem.policy import (
    PostmortemPolicy,
    PostmortemTrigger,
    TriggerType,
    PolicyConfig,
    load_policy_from_yaml,
)
from autosre.utils.deliberate import (
    DeliberateReasoner,
    DeliberationRecord,
    PAUSE_CHECKLIST_PROMPT,
)

# Multi-Tenancy (v2.2) - Enterprise SaaS support
from autosre.tenancy import (
    Tenant,
    TenantTier,
    TenantStatus,
    Workspace,
    WorkspaceType,
    Team,
    TeamRole,
    TenantContext,
    TenantIsolation,
    get_current_tenant,
    tenant_context,
    QuotaManager,
    QuotaType,
    QuotaExceededError,
    UsageTracker,
    BillingService,
    TenantMiddleware,
)

# Incident Communications (v2.4) - Automated incident communications
from autosre.comms import (
    StatusPageClient,
    StatusPageIncident,
    StatusPageUpdate,
    ComponentStatus,
    IncidentStatus,
    IncidentImpact,
    Component,
    StatusPageConfig,
    WarRoom,
    WarRoomState,
    WarRoomRole,
    WarRoomParticipant,
    WarRoomEvent,
    WarRoomEventType,
    WarRoomCoordinator,
    WarRoomConfig,
    WarRoomTimeline,
    Stakeholder,
    StakeholderGroup,
    StakeholderPriority,
    NotificationChannel,
    NotificationStatus,
    StakeholderNotifier,
    EscalationPolicy,
    EscalationLevel,
    MessageTemplate,
    TemplateContext,
    TemplateEngine,
    TemplateRegistry,
    get_builtin_templates,
)

# Chaos Engineering (v2.3) - Resilience testing
from autosre.chaos import (
    ChaosExperiment,
    ExperimentState,
    ExperimentResult,
    ExperimentConfig,
    ExperimentType,
    TargetSelector,
    ExperimentSchedule,
    ExperimentRunner,
    Fault,
    FaultType,
    FaultInjector,
    PodKillFault,
    NetworkDelayFault,
    CPUStressFault,
    MemoryStressFault,
    GameDay,
    GameDayState,
    GameDayResult,
    GameDayScenario,
    GameDayScheduler,
    GameDayRunner,
    SafetyChecker,
    SafetyRule,
    SafetyViolation,
    BlastRadius,
    BlastRadiusConfig,
    SafetyPolicy,
    SafetyLevel,
    CircuitBreaker,
    ChaosReport,
    ExperimentMetrics,
    ReportGenerator,
    ResilienceScore,
)

# SLO Management (v2.10) - Service Level Objectives
from autosre.slo import (
    # Definition
    SLIType,
    SLOPeriod,
    AlertSeverity as SLOAlertSeverity,
    ComplianceStatus,
    LatencyThreshold,
    SLIMetric,
    BurnRateWindow,
    AlertPolicy as SLOAlertPolicy,
    SLODefinition,
    SLOGroup,
    SLOManager,
    create_availability_slo,
    create_latency_slo,
    create_error_rate_slo,
    # Budget
    BudgetConsumptionRate,
    BudgetAction,
    BudgetDataPoint,
    BurnRateCalculation,
    ErrorBudgetStatus,
    BudgetPolicy,
    ErrorBudget,
    ErrorBudgetTracker,
    calculate_burn_rate,
    calculate_time_to_exhaustion,
    budget_allows_deployment,
    # Reporting
    ReportPeriod,
    ReportFormat,
    TrendDirection,
    SLOComplianceRecord,
    SLOTrend,
    ServiceSLOSummary,
    SLOReport,
    ReportGenerator as SLOReportGenerator,
    SLODashboard,
    generate_weekly_report,
    generate_monthly_report,
    format_report,
)

# Capacity Planning (v2.10) - Capacity forecasting and planning
from autosre.capacity import (
    # Forecasting
    ForecastAlgorithm,
    SeasonalityType,
    TrendDirection as CapacityTrendDirection,
    ConfidenceLevel,
    DataPoint,
    TimeSeriesData,
    ForecastConfig,
    ForecastResult,
    ForecastMetrics,
    AnomalyDetection,
    CapacityForecaster,
    quick_forecast,
    detect_seasonality,
    # Planning
    ResourceType as CapacityResourceType,
    ScalingStrategy,
    PlanningHorizon,
    RecommendationType as CapacityRecommendationType,
    RecommendationPriority as CapacityRecommendationPriority,
    CostImpact,
    ResourceSpec,
    CurrentCapacity,
    CapacityRequirement,
    ScalingRecommendation,
    CapacityPlan,
    BudgetEstimate as CapacityBudgetEstimate,
    CapacityPlanner,
    quick_capacity_check,
    estimate_scaling_needs,
    # Reporting
    ReportFormat as CapacityReportFormat,
    ReportFrequency,
    ReportSection,
    TrendIndicator,
    HealthStatus as CapacityHealthStatus,
    CapacityMetric,
    ResourceUtilization as CapacityResourceUtilization,
    CapacityTrend,
    CapacityAlert,
    CapacityInsight,
    CapacitySummary,
    CapacityReport,
    ReportConfig as CapacityReportConfig,
    CapacityReporter,
    generate_quick_report,
    get_capacity_health,
)

# Cloud Provider Integrations (v2.9) - Multi-cloud SRE
from autosre.cloud import (
    # AWS
    AWSClient,
    AWSConfig,
    AWSCredentials,
    AWSRegion,
    EC2Manager,
    EC2Instance,
    EC2InstanceState,
    EKSManager,
    EKSCluster,
    EKSClusterState,
    EKSNodeGroup,
    RDSManager,
    RDSInstance,
    RDSCluster,
    RDSEngine,
    RDSInstanceState,
    LambdaManager,
    LambdaFunction,
    LambdaRuntime,
    LambdaInvocation,
    # GCP
    GCPClient,
    GCPConfig,
    GCPCredentials,
    GCPRegion,
    GCEManager,
    GCEInstance,
    GCEInstanceState,
    GKEManager,
    GKECluster,
    GKEClusterState,
    GKENodePool,
    CloudSQLManager,
    CloudSQLInstance,
    CloudSQLDatabaseVersion,
    CloudSQLInstanceState,
    CloudFunctionManager,
    CloudFunction,
    CloudFunctionRuntime,
    # Azure
    AzureClient,
    AzureConfig,
    AzureCredentials,
    AzureRegion,
    VMManager,
    AzureVM,
    AzureVMState,
    AzureVMSize,
    AKSManager,
    AKSCluster,
    AKSClusterState,
    AKSNodePool,
    AzureSQLManager,
    AzureSQLServer,
    AzureSQLDatabase,
    AzureSQLTier,
    AzureFunctionManager,
    AzureFunction,
    AzureFunctionRuntime,
)

# Security (v2.8) - Enterprise security capabilities
from autosre.security import (
    # Scanner
    ScanType as SecurityScanType,
    Severity as SecuritySeverity,
    ScanStatus,
    VulnerabilityStatus,
    ComplianceStandard as SecurityComplianceStandard,
    ScannerConfig,
    ImageScanConfig,
    KubernetesScanConfig,
    CVSSScore,
    Vulnerability,
    ConfigurationFinding,
    NetworkExposure,
    ImageScanResult,
    KubernetesScanResult,
    ScanSummary,
    VulnerabilityScanner,
    # Audit
    SecurityEventType,
    EventSeverity,
    AuditLogDestination,
    ComplianceFramework as SecurityComplianceFramework,
    SecurityAuditConfig,
    AlertConfig as SecurityAlertConfig,
    Actor as SecurityActor,
    Resource as SecurityResource,
    SecurityEvent,
    AuditLogEntry,
    AuditQuery as SecurityAuditQuery,
    AuditQueryResult,
    ComplianceReport as SecurityComplianceReport,
    SecurityAlert,
    SecurityAuditLogger,
    # Secrets
    SecretBackend,
    SecretType,
    RotationStatus,
    AccessLevel as SecretAccessLevel,
    SecretsConfig,
    RotationConfig,
    AccessPolicy as SecretAccessPolicy,
    SecretVersion,
    SecretMetadata,
    Secret,
    SecretReference,
    RotationResult,
    SecretScanResult,
    SecretGenerator,
    SecretsManager,
)

# Database Reliability (v2.7) - Database SRE capabilities
from autosre.database import (
    # Health
    DatabaseType,
    HealthStatus as DatabaseHealthStatus,
    CheckType,
    AlertLevel as DatabaseAlertLevel,
    DatabaseConfig,
    HealthCheckConfig,
    CheckResult,
    ConnectionPoolStatus,
    ResourceStatus,
    LongRunningQuery,
    DeadlockInfo,
    HealthAlert as DatabaseHealthAlert,
    DatabaseHealthReport,
    DatabaseHealthChecker,
    MultiDatabaseHealthMonitor,
    # Performance
    QueryType,
    PerformanceLevel,
    ScanType,
    JoinType,
    OptimizationType,
    PerformanceConfig,
    QueryFingerprint,
    QueryExecution,
    QueryPlan,
    QueryStatistics,
    SlowQueryReport,
    IndexRecommendation,
    PerformanceRegression,
    QueryPerformanceAnalyzer,
    # Replication
    ReplicationRole,
    ReplicationType,
    ReplicationState,
    ReplicaHealth,
    FailoverReadiness,
    ReplicationConfig,
    ReplicationNode,
    ReplicationLag,
    ReplicationSlot,
    ReplicaStatus,
    ReplicationTopology,
    ReplicationAlert,
    LagHistoryPoint,
    ReplicationMonitor,
    # Backup
    BackupType,
    BackupStatus,
    VerificationStatus,
    StorageType,
    RecoveryPointObjective,
    BackupConfig,
    BackupMetadata,
    BackupVerification,
    RestoreTest,
    BackupSchedule,
    BackupAlert,
    RecoveryPointStatus,
    BackupSummary,
    BackupVerifier,
)

# Plugin System (v2.6) - Extensibility and custom integrations
from autosre.plugins import (
    # Base classes
    Plugin,
    SkillPlugin,
    IntegrationPlugin,
    HookPlugin,
    MiddlewarePlugin,
    # Configuration
    PluginConfig,
    PluginContext,
    PluginResult,
    # Metadata
    PluginMetadata,
    PluginState,
    PluginType,
    PluginPriority,
    PluginCapability,
    # Registry
    PluginRegistry,
    RegistryConfig,
    RegistryEvent,
    get_registry as get_plugin_registry,
    register_plugin,
    unregister_plugin,
    # Loader
    PluginLoader,
    LoaderConfig,
    discover_plugins,
    load_plugin,
    load_plugins_from_directory,
)

# AI Guardrails (v2.5) - Enterprise AI safety
from autosre.guardrails import (
    # Validators
    Validator as GuardrailValidator,
    ValidationResult,
    ValidationSeverity,
    InputValidator,
    InputValidationConfig,
    ContentCategory,
    InputSanitizer,
    SanitizationRule,
    SanitizationType,
    OutputValidator,
    OutputValidationConfig,
    OutputClassification,
    ContentFilter,
    FilterAction,
    PromptValidator,
    PromptInjectionDetector,
    InjectionType,
    SchemaValidator,
    ResponseSchemaConfig,
    # Policies
    SafetyPolicy as GuardrailSafetyPolicy,
    PolicyEngine,
    PolicyResult,
    PolicyAction,
    PolicyScope,
    RiskLevel,
    RiskAssessment,
    RiskFactor,
    RiskThreshold,
    ActionPolicy,
    ActionRestriction,
    ActionCategory,
    AllowedAction,
    RateLimiter,
    RateLimitConfig,
    RateLimitScope,
    ContextPolicy,
    SensitiveDataPolicy,
    DataClassification,
    # Approval
    ApprovalWorkflow,
    ApprovalRequest,
    ApprovalDecision,
    ApprovalStatus,
    ApprovalLevel,
    Approver,
    ApproverGroup,
    ApprovalPolicy,
    ApprovalStrategy,
    EscalationConfig,
    EscalationRule,
    ApprovalNotifier,
    NotificationConfig as ApprovalNotificationConfig,
    # Audit
    AuditTrail,
    AuditEntry,
    AuditCategory,
    AuditSeverity,
    AuditVerifier,
    IntegrityCheck,
    HashChain,
    AuditStorage,
    AuditQuery,
    AuditReport,
    ComplianceChecker,
    ComplianceFramework,
    ComplianceReport,
)

# Cost Optimization (v2.4) - FinOps for SRE
from autosre.cost import (
    CostAnalyzer,
    CostBreakdown,
    CostTrend,
    CostAllocation,
    CostMetric,
    CloudProvider,
    ResourceType,
    CostRecommendation,
    RecommendationType,
    RecommendationPriority,
    RecommendationEngine,
    SavingsEstimate,
    RecommendationStatus,
    RightsizingAnalyzer,
    RightsizingRecommendation,
    ResourceUtilization,
    InstanceSpec,
    RightsizingAction,
    UtilizationThreshold,
    CostForecaster,
    CostForecast,
    BudgetAlert,
    BudgetStatus,
    ForecastModel,
    SpendingTrend,
    AnomalyDetector,
    CostAnomaly,
)

# Workflow Automation (v2.3) - Temporal/Argo-inspired workflow engine
from autosre.workflows import (
    # Engine
    WorkflowEngine,
    WorkflowExecution,
    ExecutionStatus,
    StepExecution,
    WorkflowContext,
    # DSL
    WorkflowDefinition,
    WorkflowParser,
    WorkflowValidator,
    parse_workflow,
    parse_workflow_file,
    # Steps
    Step,
    ActionStep,
    ConditionStep,
    LoopStep,
    ParallelStep,
    SubWorkflowStep,
    StepResult,
    StepStatus,
    # Triggers
    Trigger,
    AlertTrigger,
    ScheduleTrigger,
    WebhookTrigger,
    ManualTrigger,
    TriggerEvent,
    TriggerManager,
    # Templates
    WorkflowTemplate,
    TemplateRegistry,
    get_builtin_templates,
)

# Foundation (v1) exports - maintained for compatibility
from autosre.foundation.context_store import ContextStore
from autosre.foundation.models import Service, Ownership, ChangeEvent
from autosre.logging import get_logger, configure_logging
from autosre.exceptions import (
    AutoSREError,
    ConfigurationError,
    ConnectionError,
    ContextError,
    AgentError,
    SandboxError,
    EvalError,
)

__all__ = [
    # Version
    "__version__",
    # Core v2
    "Orchestrator",
    "Investigation",
    "EpisodicMemory",
    "Episode",
    "MemoryQuery",
    "ServiceGraph",
    "ServiceNode",
    "Alert",
    "Hypothesis",
    "Evidence",
    "AgentResult",
    "InvestigationState",
    "InvestigationPlan",
    "Planner",
    "AVAILABLE_AGENTS",
    "Synthesizer",
    "Synthesis",
    "WriteupGenerator",
    "IncidentReport",
    "LLMRouter",
    "TerminalReporter",
    # On-call & Postmortem (v2.1)
    "AlertQualityValidator",
    "AlertQualityResult",
    "REQUIRED_ALERT_FIELDS",
    "OnCallLoadTracker",
    "ShiftStatus",
    "LoadStatus",
    "MAX_INCIDENTS_PER_SHIFT",
    "SHIFT_HOURS",
    # On-Call Management (Extended v2.1+)
    # Schedule
    "ScheduleType",
    "DayOfWeek",
    "ScheduleRestrictionType",
    "OverrideReason",
    "TimeRange",
    "ScheduleRestriction",
    "ScheduleLayer",
    "ScheduleOverride",
    "OnCallSchedule",
    "ScheduleManager",
    "create_weekly_schedule",
    "create_follow_the_sun_schedule",
    # Rotation
    "RotationType",
    "RotationFrequency",
    "UserAvailability",
    "RotationRole",
    "UserStats",
    "UserAvailabilityWindow",
    "RotationConstraint",
    "RotationMember",
    "Rotation",
    "RotationManager",
    "create_simple_rotation",
    "create_tiered_rotation",
    # Escalation
    "EscalationTrigger",
    "NotificationMethod",
    "OnCallEscalationStatus",
    "TargetType",
    "NotificationTarget",
    "OnCallEscalationLevel",
    "OnCallEscalationPolicy",
    "EscalationEvent",
    "ActiveEscalation",
    "EscalationEngine",
    "create_simple_escalation_policy",
    "create_tiered_escalation_policy",
    # Handoff
    "HandoffStatus",
    "HandoffItemType",
    "HandoffItemPriority",
    "HandoffItemStatus",
    "HandoffItem",
    "IncidentSummary",
    "ShiftSummary",
    "Handoff",
    "HandoffTemplate",
    "HandoffManager",
    "create_quick_handoff",
    "generate_handoff_checklist",
    "PostmortemGenerator",
    "PostmortemDraft",
    "ActionItem",
    "ActionPriority",
    "AIPerformanceReview",
    "PostmortemPolicy",
    "PostmortemTrigger",
    "TriggerType",
    "PolicyConfig",
    "load_policy_from_yaml",
    "DeliberateReasoner",
    "DeliberationRecord",
    "PAUSE_CHECKLIST_PROMPT",
    # Multi-Tenancy (v2.2)
    "Tenant",
    "TenantTier",
    "TenantStatus",
    "Workspace",
    "WorkspaceType",
    "Team",
    "TeamRole",
    "TenantContext",
    "TenantIsolation",
    "get_current_tenant",
    "tenant_context",
    "QuotaManager",
    "QuotaType",
    "QuotaExceededError",
    "UsageTracker",
    "BillingService",
    "TenantMiddleware",
    # Incident Communications (v2.4)
    "StatusPageClient",
    "StatusPageIncident",
    "StatusPageUpdate",
    "ComponentStatus",
    "IncidentStatus",
    "IncidentImpact",
    "Component",
    "StatusPageConfig",
    "WarRoom",
    "WarRoomState",
    "WarRoomRole",
    "WarRoomParticipant",
    "WarRoomEvent",
    "WarRoomEventType",
    "WarRoomCoordinator",
    "WarRoomConfig",
    "WarRoomTimeline",
    "Stakeholder",
    "StakeholderGroup",
    "StakeholderPriority",
    "NotificationChannel",
    "NotificationStatus",
    "StakeholderNotifier",
    "EscalationPolicy",
    "EscalationLevel",
    "MessageTemplate",
    "TemplateContext",
    "TemplateEngine",
    # Chaos Engineering (v2.3) - Resilience testing
    "ChaosExperiment",
    "ExperimentState",
    "ExperimentResult",
    "ExperimentConfig",
    "ExperimentType",
    "TargetSelector",
    "ExperimentSchedule",
    "ExperimentRunner",
    "Fault",
    "FaultType",
    "FaultInjector",
    "PodKillFault",
    "NetworkDelayFault",
    "CPUStressFault",
    "MemoryStressFault",
    "GameDay",
    "GameDayState",
    "GameDayResult",
    "GameDayScenario",
    "GameDayScheduler",
    "GameDayRunner",
    "SafetyChecker",
    "SafetyRule",
    "SafetyViolation",
    "BlastRadius",
    "BlastRadiusConfig",
    "SafetyPolicy",
    "SafetyLevel",
    "CircuitBreaker",
    "ChaosReport",
    "ExperimentMetrics",
    "ReportGenerator",
    "ResilienceScore",
    # Workflow Automation (v2.3)
    "WorkflowEngine",
    "WorkflowExecution",
    "ExecutionStatus",
    "StepExecution",
    "WorkflowContext",
    "WorkflowDefinition",
    "WorkflowParser",
    "WorkflowValidator",
    "parse_workflow",
    "parse_workflow_file",
    "Step",
    "ActionStep",
    "ConditionStep",
    "LoopStep",
    "ParallelStep",
    "SubWorkflowStep",
    "StepResult",
    "StepStatus",
    "Trigger",
    "AlertTrigger",
    "ScheduleTrigger",
    "WebhookTrigger",
    "ManualTrigger",
    "TriggerEvent",
    "TriggerManager",
    "WorkflowTemplate",
    "TemplateRegistry",
    "get_builtin_templates",
    # Cost Optimization (v2.4)
    "CostAnalyzer",
    "CostBreakdown",
    "CostTrend",
    "CostAllocation",
    "CostMetric",
    "CloudProvider",
    "ResourceType",
    "CostRecommendation",
    "RecommendationType",
    "RecommendationPriority",
    "RecommendationEngine",
    "SavingsEstimate",
    "RecommendationStatus",
    "RightsizingAnalyzer",
    "RightsizingRecommendation",
    "ResourceUtilization",
    "InstanceSpec",
    "RightsizingAction",
    "UtilizationThreshold",
    "CostForecaster",
    "CostForecast",
    "BudgetAlert",
    "BudgetStatus",
    "ForecastModel",
    "SpendingTrend",
    "AnomalyDetector",
    "CostAnomaly",
    # AI Guardrails (v2.5)
    "GuardrailValidator",
    "ValidationResult",
    "ValidationSeverity",
    "InputValidator",
    "InputValidationConfig",
    "ContentCategory",
    "InputSanitizer",
    "SanitizationRule",
    "SanitizationType",
    "OutputValidator",
    "OutputValidationConfig",
    "OutputClassification",
    "ContentFilter",
    "FilterAction",
    "PromptValidator",
    "PromptInjectionDetector",
    "InjectionType",
    "SchemaValidator",
    "ResponseSchemaConfig",
    "GuardrailSafetyPolicy",
    "PolicyEngine",
    "PolicyResult",
    "PolicyAction",
    "PolicyScope",
    "RiskLevel",
    "RiskAssessment",
    "RiskFactor",
    "RiskThreshold",
    "ActionPolicy",
    "ActionRestriction",
    "ActionCategory",
    "AllowedAction",
    "RateLimiter",
    "RateLimitConfig",
    "RateLimitScope",
    "ContextPolicy",
    "SensitiveDataPolicy",
    "DataClassification",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "ApprovalDecision",
    "ApprovalStatus",
    "ApprovalLevel",
    "Approver",
    "ApproverGroup",
    "ApprovalPolicy",
    "ApprovalStrategy",
    "EscalationConfig",
    "EscalationRule",
    "ApprovalNotifier",
    "ApprovalNotificationConfig",
    "AuditTrail",
    "AuditEntry",
    "AuditCategory",
    "AuditSeverity",
    "AuditVerifier",
    "IntegrityCheck",
    "HashChain",
    "AuditStorage",
    "AuditQuery",
    "AuditReport",
    "ComplianceChecker",
    "ComplianceFramework",
    "ComplianceReport",
    # Plugin System (v2.6)
    "Plugin",
    "SkillPlugin",
    "IntegrationPlugin",
    "HookPlugin",
    "MiddlewarePlugin",
    "PluginConfig",
    "PluginContext",
    "PluginResult",
    "PluginMetadata",
    "PluginState",
    "PluginType",
    "PluginPriority",
    "PluginCapability",
    "PluginRegistry",
    "RegistryConfig",
    "RegistryEvent",
    "get_plugin_registry",
    "register_plugin",
    "unregister_plugin",
    "PluginLoader",
    "LoaderConfig",
    "discover_plugins",
    "load_plugin",
    "load_plugins_from_directory",
    # Database Reliability (v2.7)
    "DatabaseType",
    "DatabaseHealthStatus",
    "CheckType",
    "DatabaseAlertLevel",
    "DatabaseConfig",
    "HealthCheckConfig",
    "CheckResult",
    "ConnectionPoolStatus",
    "ResourceStatus",
    "LongRunningQuery",
    "DeadlockInfo",
    "DatabaseHealthAlert",
    "DatabaseHealthReport",
    "DatabaseHealthChecker",
    "MultiDatabaseHealthMonitor",
    "QueryType",
    "PerformanceLevel",
    "ScanType",
    "JoinType",
    "OptimizationType",
    "PerformanceConfig",
    "QueryFingerprint",
    "QueryExecution",
    "QueryPlan",
    "QueryStatistics",
    "SlowQueryReport",
    "IndexRecommendation",
    "PerformanceRegression",
    "QueryPerformanceAnalyzer",
    "ReplicationRole",
    "ReplicationType",
    "ReplicationState",
    "ReplicaHealth",
    "FailoverReadiness",
    "ReplicationConfig",
    "ReplicationNode",
    "ReplicationLag",
    "ReplicationSlot",
    "ReplicaStatus",
    "ReplicationTopology",
    "ReplicationAlert",
    "LagHistoryPoint",
    "ReplicationMonitor",
    "BackupType",
    "BackupStatus",
    "VerificationStatus",
    "StorageType",
    "RecoveryPointObjective",
    "BackupConfig",
    "BackupMetadata",
    "BackupVerification",
    "RestoreTest",
    "BackupSchedule",
    "BackupAlert",
    "RecoveryPointStatus",
    "BackupSummary",
    "BackupVerifier",
    # Security (v2.8)
    "SecurityScanType",
    "SecuritySeverity",
    "ScanStatus",
    "VulnerabilityStatus",
    "SecurityComplianceStandard",
    "ScannerConfig",
    "ImageScanConfig",
    "KubernetesScanConfig",
    "CVSSScore",
    "Vulnerability",
    "ConfigurationFinding",
    "NetworkExposure",
    "ImageScanResult",
    "KubernetesScanResult",
    "ScanSummary",
    "VulnerabilityScanner",
    "SecurityEventType",
    "EventSeverity",
    "AuditLogDestination",
    "SecurityComplianceFramework",
    "SecurityAuditConfig",
    "SecurityAlertConfig",
    "SecurityActor",
    "SecurityResource",
    "SecurityEvent",
    "AuditLogEntry",
    "SecurityAuditQuery",
    "AuditQueryResult",
    "SecurityComplianceReport",
    "SecurityAlert",
    "SecurityAuditLogger",
    "SecretBackend",
    "SecretType",
    "RotationStatus",
    "SecretAccessLevel",
    "SecretsConfig",
    "RotationConfig",
    "SecretAccessPolicy",
    "SecretVersion",
    "SecretMetadata",
    "Secret",
    "SecretReference",
    "RotationResult",
    "SecretScanResult",
    "SecretGenerator",
    "SecretsManager",
    # Cloud Provider Integrations (v2.9)
    # AWS
    "AWSClient",
    "AWSConfig",
    "AWSCredentials",
    "AWSRegion",
    "EC2Manager",
    "EC2Instance",
    "EC2InstanceState",
    "EKSManager",
    "EKSCluster",
    "EKSClusterState",
    "EKSNodeGroup",
    "RDSManager",
    "RDSInstance",
    "RDSCluster",
    "RDSEngine",
    "RDSInstanceState",
    "LambdaManager",
    "LambdaFunction",
    "LambdaRuntime",
    "LambdaInvocation",
    # GCP
    "GCPClient",
    "GCPConfig",
    "GCPCredentials",
    "GCPRegion",
    "GCEManager",
    "GCEInstance",
    "GCEInstanceState",
    "GKEManager",
    "GKECluster",
    "GKEClusterState",
    "GKENodePool",
    "CloudSQLManager",
    "CloudSQLInstance",
    "CloudSQLDatabaseVersion",
    "CloudSQLInstanceState",
    "CloudFunctionManager",
    "CloudFunction",
    "CloudFunctionRuntime",
    # Azure
    "AzureClient",
    "AzureConfig",
    "AzureCredentials",
    "AzureRegion",
    "VMManager",
    "AzureVM",
    "AzureVMState",
    "AzureVMSize",
    "AKSManager",
    "AKSCluster",
    "AKSClusterState",
    "AKSNodePool",
    "AzureSQLManager",
    "AzureSQLServer",
    "AzureSQLDatabase",
    "AzureSQLTier",
    "AzureFunctionManager",
    "AzureFunction",
    "AzureFunctionRuntime",
    # SLO Management (v2.10)
    "SLIType",
    "SLOPeriod",
    "SLOAlertSeverity",
    "ComplianceStatus",
    "LatencyThreshold",
    "SLIMetric",
    "BurnRateWindow",
    "SLOAlertPolicy",
    "SLODefinition",
    "SLOGroup",
    "SLOManager",
    "create_availability_slo",
    "create_latency_slo",
    "create_error_rate_slo",
    "BudgetConsumptionRate",
    "BudgetAction",
    "BudgetDataPoint",
    "BurnRateCalculation",
    "ErrorBudgetStatus",
    "BudgetPolicy",
    "ErrorBudget",
    "ErrorBudgetTracker",
    "calculate_burn_rate",
    "calculate_time_to_exhaustion",
    "budget_allows_deployment",
    "ReportPeriod",
    "ReportFormat",
    "TrendDirection",
    "SLOComplianceRecord",
    "SLOTrend",
    "ServiceSLOSummary",
    "SLOReport",
    "SLOReportGenerator",
    "SLODashboard",
    "generate_weekly_report",
    "generate_monthly_report",
    "format_report",
    # Capacity Planning (v2.10)
    # Forecasting
    "ForecastAlgorithm",
    "SeasonalityType",
    "CapacityTrendDirection",
    "ConfidenceLevel",
    "DataPoint",
    "TimeSeriesData",
    "ForecastConfig",
    "ForecastResult",
    "ForecastMetrics",
    "AnomalyDetection",
    "CapacityForecaster",
    "quick_forecast",
    "detect_seasonality",
    # Planning
    "CapacityResourceType",
    "ScalingStrategy",
    "PlanningHorizon",
    "CapacityRecommendationType",
    "CapacityRecommendationPriority",
    "CostImpact",
    "ResourceSpec",
    "CurrentCapacity",
    "CapacityRequirement",
    "ScalingRecommendation",
    "CapacityPlan",
    "CapacityBudgetEstimate",
    "CapacityPlanner",
    "quick_capacity_check",
    "estimate_scaling_needs",
    # Reporting
    "CapacityReportFormat",
    "ReportFrequency",
    "ReportSection",
    "TrendIndicator",
    "CapacityHealthStatus",
    "CapacityMetric",
    "CapacityResourceUtilization",
    "CapacityTrend",
    "CapacityAlert",
    "CapacityInsight",
    "CapacitySummary",
    "CapacityReport",
    "CapacityReportConfig",
    "CapacityReporter",
    "generate_quick_report",
    "get_capacity_health",
    # Foundation (v1)
    "ContextStore",
    "Service",
    "Ownership",
    "ChangeEvent",
    # Logging
    "get_logger",
    "configure_logging",
    # Exceptions
    "AutoSREError",
    "ConfigurationError",
    "ConnectionError",
    "ContextError",
    "AgentError",
    "SandboxError",
    "EvalError",
]
