apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookstore-api
  namespace: bookstore
  labels:
    app: bookstore-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bookstore-api
  namespaceSelector:
    matchNames:
      - bookstore
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
