apiVersion: v1
kind: Service
metadata:
  name: bookstore-api
  namespace: bookstore
  labels:
    app: bookstore-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: bookstore-api
