{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autosre.fullname" . }}-ui
  labels:
    {{- include "autosre.ui.labels" . | nindent 4 }}
  {{- with (merge .Values.ui.podAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.ui.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "autosre.ui.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "autosre.ui.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "autosre.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: {{ include "autosre.ui.image" . }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_URL
              value: "http://{{ include "autosre.fullname" . }}-api:{{ .Values.api.service.port }}"
            {{- with .Values.ui.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.ui.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ui.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            {{- with .Values.ui.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        {{- with .Values.ui.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
