{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autosre.fullname" . }}-api
  labels:
    {{- include "autosre.api.labels" . | nindent 4 }}
  annotations:
    {{- include "autosre.annotations" . | nindent 4 }}
    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autosre.api.selectorLabels" . | nindent 4 }}
{{- end }}
